- id: nixos-backup-config
  name: Backup-NixOS-Configs
  description: This hook copies all files at /etc/nixos to $GIT_DIR/nixos/backup.
  entry: hooks/backup-nixos.sh
  language: script
- id: nixos-build
  name: Building Nix Packages
  description: This runs nix-build on all files passed to it.
  entry: hooks/nix/nix-build.sh
  language: script
  files: packages\.nix$
- id: nix-flake-check
  name: Check Nix flakes
  description: Validates Nix flakes using 'nix flake check'
  entry: hooks/nix/nix-flake-check.sh
  language: script
  files: flake\.nix$
  pass_filenames: true
- id: nix-build-check
  name: Check Nix builds
  description: Tests that Nix expressions build successfully
  entry: hooks/nix/nix-build-check.sh
  language: script
  files: (default|shell)\.nix$
  pass_filenames: true
- id: nix-darwin-check
  name: Check nix-darwin configuration
  description: Validates nix-darwin configurations
  entry: hooks/nix/nix-darwin-check.sh
  language: script
  files: darwin.*\.nix$
  pass_filenames: true
- id: nix-home-manager-check
  name: Check home-manager configuration
  description: Validates home-manager configurations
  entry: hooks/nix/nix-home-manager-check.sh
  language: script
  files: (home|users/.*|home-manager/.*)\.nix$
  pass_filenames: true
- id: nix-fmt
  name: Format Nix files
  description: Formats Nix files using nixpkgs-fmt or alejandra
  entry: hooks/nix/nix-fmt.sh
  language: script
  files: \.nix$
  pass_filenames: true
  args: [--formatter=nixpkgs-fmt]
- id: nix-lint
  name: Lint Nix files
  description: Lints Nix files using statix and optionally deadnix
  entry: hooks/nix/nix-lint.sh
  language: script
  files: \.nix$
  pass_filenames: true
- id: op-ggshield-img
  name: 1PW-GGShield
  description: This hook downloads and runs a docker container that calls `op run -- ggshield secret scan pre-commit`.
  entry: docker.com/op-ggshield:latest
  language: docker_image
  types: [text]
- id: nixos-update-config
  name: Update-NixOS-Configs
  description: "NOT IMPLEMENTED: This hook copies all files at $GIT_DIR/nixos/WIP to /etc/nixos."
  entry: hooks/updated-vm.sh
  language: script
  stages:
    - post-checkout
    - post-merge
- id: bear-witness
  name: Creating Attestations
  description: "NOT IMPLEMENTED: This hook runs in-toto `witness` to attest a step of the SWSC."
  entry: hooks/witness.sh
  language: script
  stages: [pre-commit, post-commit, post-checkout, pre-push]
- id: csslint
  name: "UNTESTED: csslint"
  entry: hooks/web/css/csslint.sh
  language: script
  files: \.css$
  args: []
  minimum_pre_commit_version: 0.7.0
- id: eslint
  name: "UNTESTED: eslint"
  description: ""
  entry: hooks/web/js/eslint.sh
  language: script
  "types": [javascript]
  args: []
  require_serial: false
  minimum_pre_commit_version: "0"
- id: fixmyjs
  name: "UNTESTED: fixmyjs"
  description: ""
  entry: hooks/web/js/fixmyjs.sh
  language: script
  "types": [javascript]
  args: []
  require_serial: false
  minimum_pre_commit_version: "0"
- id: jshint
  name: "UNTESTED: jshint"
  description: ""
  entry: hooks/web/js/jshint.sh
  language: script
  # language: node
  "types": [javascript]
  args: []
  require_serial: false
  minimum_pre_commit_version: "0"
- id: scss-lint
  name: scss_lint
  description: ""
  entry: hooks/web/scss/scss-lint.sh
  language: script
  # language: ruby
  "types": [scss]
  args: []
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: "0"
- id: yamlfmt
  name: "UNTESTED: yamlfmt"
  description: This hook uses github.com/google/yamlfmt to format yaml files. Requires golang >1.18 to be installed.
  entry: hooks/configs/yamlfmt.sh
  language: script
  types: [yaml]
  args: []
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: "0"
- id: commitlint
  name: "UNTESTED: commitlint"
  description: Commitlint hook
  entry: hooks/commits/commitlint.sh
  language: script
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: "0"
  pass_filenames: false
  always_run: true
- id: gitlint
  name: "UNTESTED: gitlint"
  description: Checks your git commit messages for style.
  entry: hooks/commits/gitlint.sh
  language: script
  additional_dependencies: ["./gitlint-core[trusted-deps]"]
  args: [--staged, --msg-filename]
  stages: [commit-msg]
- id: gitlint-ci
  name: "UNTESTED: gitlint-ci"
  language: script
  additional_dependencies: ["./gitlint-core[trusted-deps]"]
  entry: hooks/commits/gitlint.sh
  always_run: true
  pass_filenames: false
  stages: [manual]
- id: commitizen
  name: "UNTESTED: commitizen check"
  description: >
    Check whether the current commit message follows committing rules. Allow
    empty commit messages by default, because they typically indicate to Git
    that the commit should be aborted.
  entry: cz check
  args: [--allow-abort, --commit-msg-file]
  stages: [commit-msg]
  language: script
  minimum_pre_commit_version: "1.4.3"
- id: commitizen-branch
  name: "UNTESTED: commitizen check branch"
  description: >
    Check all commit messages that are already on the current branch but not the
    default branch on the origin repository. Useful for checking messages after
    the fact (e.g., pre-push or in CI) without an expensive check of the entire
    repository history.
  entry: cz check
  args: [--rev-range, origin/HEAD..HEAD]
  always_run: true
  pass_filenames: false
  language: script
  minimum_pre_commit_version: "1.4.3"
- id: actionlint
  # name: Lint GitHub Actions workflow files
  name: "UNTESTED: actionlint"
  description: Runs actionlint to lint GitHub Actions workflow files
  language: golang
  types: ["yaml"]
  files: ^\.github/workflows/
  entry: actionlint
  minimum_pre_commit_version: 3.0.0
- id: actionlint-docker
  # name: Lint GitHub Actions workflow files
  name: "UNTESTED: actionlint-docker"
  description: Runs actionlint Docker image to lint GitHub Actions workflow files
  language: docker_image
  types: ["yaml"]
  files: ^\.github/workflows/
  entry: docker.io/rhysd/actionlint:1.7.1
- id: actionlint-system
  # name: Lint GitHub Actions workflow files
  name: "UNTESTED: actionlint-system"
  description: Runs system-installed actionlint to lint GitHub Actions workflow files
  language: script
  types: ["yaml"]
  files: ^\.github/workflows/
  entry: hooks/ci/github.sh
- id: pluralith
  name: "Generating Terraform Diagram"
  description: Generates a graph of the currently described resources. Takes (optional) 'apikey' & (optional) 'binpath' as arguments.
  entry: hooks/terraform/pluralith.sh
  language: script
  files: \.tf$
  types: [hcl, yaml]
  # args: []
  require_serial: false
  additional_dependencies: []
  minimum_pre_commit_version: "0"
  pass_filenames: false
# - id: tfupdate
#   name: "UNTESTED: tfupdate"
#   description: Updates version constraints for Terraform, TF Providers, & TF Modules.
#   entry: hooks/terraform/tfupdate.sh
#   language: script
#   types: [file, yaml]
#   args: []
#   require_serial: false
#   # additional_dependencies: []
#   minimum_pre_commit_version: '0'
- id: tfupdate
  name: "UNTESTED: tfupdate (providers)"
  description: Updates version constraints for Terraform, TF Providers, & TF Modules.
  entry: hooks/terraform/tfupdate.sh
  language: script
  files: \.tf$
  args:
    - --provider=aws
  always_run: true
  require_serial: false
  # additional_dependencies: []
  minimum_pre_commit_version: "0"
- id: dead-links
  name: "Check Markdown Links"
  description: Checks markdown files for dead relative links.
  entry: hooks/docs/dead-links.sh
  language: script
  files: \.md$
  types:
    - markdown
- id: backup-nixos-config
  name: Backup-NixOS-Configs
  description: This hook copies all files at /etc/nixos to $GIT_DIR/nixos/backup.
  entry: hooks/backup-nixos.sh
  language: script
- id: op-ggshield-img
  name: 1PW-GGShield
  description: This hook downloads and runs a docker container that calls `op run -- ggshield secret scan pre-commit`.
  entry: docker.com/op-ggshield:latest
  language: docker_image
  types: [text]
- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: rustc
  name: rustc
  description: Run `cargo rustc` following the cargo.toml file
  entry: cargo rustc
  language: system
  always_run: true
  args: []
  types: [rust]
  pass_filenames: false
- id: build-docs
  name: build-docs
  description: Run `cargo doc` to build rust documentation
  entry: cargo doc
  language: system
  always_run: true
  args: []
  types: [rust]
  pass_filenames: false
- id: generate-report
  name: generate-report
  description: Run `cargo report future-incompat` to check for future incompatibilities
  entry: cargo report future-incompat
  language: system
  args: []
  types: [rust]
  pass_filenames: false
- id: cargo-bench
  name: cargo-bench
  description: Run `cargo bench` to Compile and execute benchmarks.
  entry: cargo bench
  language: system
  args: []
  types: [rust]
  pass_filenames: false
- id: validate-frontmatter
  name: Validate Markdown Frontmatter
  description: Validate frontmatter UUIDs and cross-references in markdown files
  entry: hooks/python/validate-frontmatter/validate_frontmatter
  language: python
  files: \.md$
  exclude: ^(README\.md|CHANGELOG\.md|\.github/.*\.md|\.ai/templates/.*|\.ai/artifacts/.*|docs/prompts/.*|docs/project-knowledge/user/.*)$
  pass_filenames: true
  additional_dependencies: []
